version: '2'

services:
    nginx:
        image: nginx
        container_name: nginx
        volumes: 
            - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./client/dist:/etc/nginx/http"
        ports: 
            - 8080:80
